In [4]:
#pip install pomegranate

In [5]:
#imports
import pandas as pd
import numpy as np
from pomegranate import *

In [10]:
#reads in the dummy tables
df1 = pd.read_excel("dummy1.xlsx");
df2 = pd.read_excel("dummy2.xlsx");

In [11]:
#we drop insignifigant columns we remove in order to speed up initialization 
toDrop = ['ID', 'Age', 'Sex', 'Time_Providing_Care', 'Race', 'Caregiver_for_Veteran', 'Other_caregiver','Veteran','Other',
                'Use_of_Video_Conferencing', 'Hypertension_high_blood_pressure_Chronic_Conditions', 'Hyperlipidemia_high_blood_cholesterol_or_triglyceride_levels_Chronic_Conditions', 
                 'Allergies', 'sinusitis_and_other_upper_respiratory_conditions_Chronic_Conditions', 'Arthritis_Chronic_Conditions', 'Mood_Disorder_depression_and_bipolar_disorder_Chronic_Conditions', 
                'Diabetes_Type1_and_Type_2_Chronic_Conditions', 'Anxiety_Disorder_Chronic_Conditions', 'Asthma_Chronic_Conditions', 'Coronary_artery_disease_includes_myocardial_infarction_heart_attack_Chronic_Conditions', 
                'Thyroid_disorder_Chronic_Conditions', 'Chronic_obstructive_lung_disease_and_bronchiectasis_Chronic_Condition', 'Traumatic_Brain_Injury__TBI_Chronic_Conditions', 'Post_Traumatic_Stress_Disorder_PTSD_Chronic_Conditions', 
                'None_of_the_above__Chronic_Conditions', 'Caregivers_Portal_Video_Use', 'Family_members__Portal_Video_Us', 'Friends_Portal_Video_Use', 'Others_Portal_Video_Use', 'Not_using_Portal_video_Portal_Video_Use', 'Portal_Chronic_Disease_Management_Help', 
                'SMS_text_Connection_Technology_Use', 'Phone_Connection_Technology_Use', 'Video_Portal_Connection_Technology_Use', 'Other_Connection_Technology_Use']
dropped1 = df1.drop(columns=toDrop)
dropped2 = df2.drop(columns=toDrop)

In [12]:
coding = {
    'Agree': 1,
    'StronglyAgree': 2,
    'Strongly Agree': 2,
    'StronglyDisagree': -2,
    'Strongly Disagree': -2,
    'Disagree': -1,
    'Neutral': 0,
    'Yes': 1,
    'No': -1,
    'Rarely':-1,
    'Never':-2,
    'Sometimes':1,
    'Always':2,
    '0':0,
    '1':1
}
def f(s):
    l = []
    for b in s:
        if (b in coding):
            l.append(coding[b])
        else:
            l.append(b)
    return pd.Series(l)

In [13]:
#makes all data numerical
data1 = dropped1.apply(f, axis=0)
data2 = dropped2.apply(f, axis=0)

In [14]:
#identifies data as being from before, or after portal usage and merges dataframes
data1['before']=np.full(data1.shape[0], 1)
data2['before']=np.full(data1.shape[0], 0)
x = pd.concat([data1, data2])
x

,Motivation,Physical_Exhaustion,Life_Satisfaction,Relationship_Impact,Concern_About_Future,Competing_Demand,Demands_Strength,Health_Change,Financial_Decrease,Same_Self,...,Difficult_to_make_friends,Need_Company,Unable_To_Communicate,Feel_Completely_Alone,Waiting_for_Contact,No_One_Understands_Me,Cant_Tolerate_Being_Alone,No_One_To_Talk_To,Unhappy_Alone,before
0,0,0,0,2,1,2,2,1,-2,1,...,2,-2,-1,1,1,-2,2,-2,0,1
1,1,0,-2,1,-2,2,-2,2,2,2,...,-2,-2,-1,1,2,-1,-1,2,0,1
2,0,0,0,2,1,2,-1,0,2,-1,...,1,2,2,1,-2,1,2,1,0,1
3,0,1,1,-2,-2,2,-2,2,-1,2,...,2,1,-1,-2,2,-2,1,-2,1,1
4,1,1,-1,-1,2,1,-2,0,0,0,...,-1,-1,-1,2,-1,1,2,-2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1,0,0,0,2,1,2,1,-1,1,...,1,-1,-1,1,-1,-2,2,1,0,0
496,0,0,0,-2,-1,0,1,-2,1,-2,...,2,-2,-1,2,1,-1,-2,-1,0,0
497,0,1,1,2,-1,-2,2,-1,-2,2,...,2,-2,-1,-1,-1,-1,-1,-2,1,0
498,0,1,1,2,2,0,-2,1,0,-1,...,-2,2,1,1,2,1,1,-2,1,0
499,0,1,2,0,2,1,2,0,0,-1,...,2,-2,-1,2,-1,-2,-1,1,1,0

In [ ]:
#creates Bayesian model using data
model = BayesianNetwork.from_samples(x)